---
source: Rmd
title: "Installing Bioconductor"
teaching: XX
exercises: XX
questions:
- "How do I install Bioconductor packages?"
objectives:
- "Install BiocManager."
- "Install Bioconductor packages."
keypoints:
- "The BiocManager package is available from the CRAN repository."
- "BiocManager is used to install Bioconductor packages (but also from CRAN and GitHub), and check for updates."
- "BiocManager safely manages packages from the incremental releases of Bioconductor."
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("02-")
```

# Installing packages

```{r, eval=FALSE}
install.packages("BiocManager")
BiocManager::install("BiocPkgTools")
BiocManager::version()
BiocManager::valid()
```

* Release cycle - release vs devel

# Explore the package universe

```{r, message=FALSE}
library(BiocPkgTools)
```

> ## Contribute!
>
> - Demonstrate relevant functions of the `r BiocStyle::Biocpkg("BiocPkgTools")` package.
>
{: .callout}

# Finding a suitable package

* biocViews
