---
source: Rmd
title: "Getting help"
teaching: XX
exercises: XX
questions:
- "How do I access package documentation?"
- "Where can I find help online?"
- "Where can I ask questions to package developers and users?"
objectives:
- "Identify online resources for help."
- "Access package documentation."
keypoints:
- "The `browseVignettes()` function is recommended to access the vignette(s) installed with each package."
- "Vignettes can also be accessed on the Bioconductor website, but beware of differences between package versions!"
- "The Bioconductor main website contains general information, package documentation, and course materials."
- "The Bioconductor support site is the recommended place to contact developers and ask questions."
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("03-")
```

# Getting help with Bioconductor packages

Help about Bioconductor packages and best practices is available in several places.
Often, the best source of help depends on the situation at hand:

- Are you trying to identify the best package for a particular task?
- Are you trying to use a package for the very first time?
- Are you unsure about best practices to use and combine multiple packages and functions in a sensible workflow?
- Is a function throwing an error when you apply it to your data?
- Do you have questions about the theory or methodology implemented in a particular package or function?

In the next sections, we describe different sources of help available to Bioconductor users, and situations where each of them are most useful.

# The Bioconductor website

The main [Bioconductor website][bioc-website] provides a host of resources, all freely available without even the need to install R or any Bioconductor package.

In particular, the [biocViews][biocviews-site] page is a great way to thematically explore the collection of packages and identify Bioconductor packages providing a certain functionality.

Furthermore, the website also collects materials from [courses and conferences][bioc-courses-conferences-materials], including presentations, video recordings, and teaching materials.

By nature, individual training materials are often tied to a specific version of Bioconductor packages.
As such, they provide a snapshot of best practices at a particular point in time, may become outdated with respect to subsequent Bioconductor release.
However, they generally provide high-quality contents designed by experienced package developers and the [Bioconductor Core Team][bioc-core-team] themselves.

> ## Contribute!
> 
> Add content about:
>
> - Course materials
>
{: .callout}

# Package landing pages

Package landing pages contains useful information to read before and after installing a package.

Before installing a package, as prospective users, we can consult the package description and vignettes, to decide whether the package is relevant to the task that we wish to perform.

After installing the package, we can consult the `BugReports` field for the URL where bugs should be reported, and the "Build Report" link can be checked to verify whether the package passes all daily checks on the build system.
Sometimes, packages that used to work can cease to pass daily tests due to updates in their own dependencies, until they are updated themselves.

For each package, the landing page links to the reference manual and vignettes for the latest version of the package available on for a given release of Bioconductor.
However, the safest way is to access the vignettes of locally installed packages.

Each package has a landing page for each release of Bioconductor since the package was added to the repository, e.g.:

- <https://www.bioconductor.org/packages/3.14/bioc/html/BiocVersion.html>
- <https://www.bioconductor.org/packages/3.13/bioc/html/BiocVersion.html>
- <https://www.bioconductor.org/packages/3.12/bioc/html/BiocVersion.html>
- ...


In the URL of a package landing page, we can replace the version number by the word "release" or "devel" to access the landing page of the latest stable release or development version, respectively.
For instance:

- <https://www.bioconductor.org/packages/release/bioc/html/BiocPkgTools.html>.
- <https://www.bioconductor.org/packages/devel/bioc/html/BiocPkgTools.html>.


# Package vignettes

> ## Contribute!
> 
> Add content about:
>
> - Each Bioconductor package is required to include at least one vignette. Many packages have more.
> - Vignettes are expected to demonstrate usage of the package in a typical workflow that users would face.
>
{: .callout}


# The Bioconductor support site

> ## Contribute!
> 
> Add content about:
>
> - Creating an account
> - Searching and posting
> - Upvoting answers
> - Accepting answers
>
{: .callout}


# Workflows

> ## Contribute!
> 
> Add content about:
>
> - Workflow packages
> - <https://www.bioconductor.org/packages/release/BiocViews.html#___Workflow>
>
{: .callout}

[bioc-website]: https://www.bioconductor.org/
[biocviews-site]: https://www.bioconductor.org/packages/release/BiocViews.html
[bioc-courses-conferences-materials]: https://bioconductor.org/help/course-materials/
[bioc-core-team]: https://www.bioconductor.org/about/core-team/
